name: Build and Publish Package

on:
  create

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  publish_apisix:
    name: Build and Publish RPM Package
    runs-on: ubuntu-18.04
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Extract Tags name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"

      - name: Extract Tags Type
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag_type
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Set env TARGET_APP
        run: |
          if [[ ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }} ]]; then
              echo "TARGET_APP=apisix-base" >> "$GITHUB_ENV"
          else if [[ ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }} ]]; then
              echo "TARGET_APP=apisix" >> "$GITHUB_ENV"
          else if [[ ${{ startsWith(steps.tag_type.outputs.version, 'dashboard/') }} ]]; then
              echo "TARGET_APP=apisix-dashboard" >> "$GITHUB_ENV"
          fi

      - name: Build target app RPM Package
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
        env: 
          TAG_VERSION: ${{ steps.tag_env.outputs.version }}
          TARGET_APP: ${{ env.TARGET_APP }}
        run: |
          # build
          echo "TAG_VERSION: " ${TAG_VERSION}
          echo "TARGET_APP: " ${TARGET_APP}
          make package type=rpm app=${TARGET_APP} openresty=apisix-base checkout=${TAG_VERSION} version=${TAG_VERSION} image_base=centos image_tag=7
          mv ./output/${TARGET_APP}-${TAG_VERSION}-0.el7.x86_64.rpm ./

      - name: Upload apisix Artifact
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "apisix-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"
          path: "./apisix-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"

      - name: Upload apisix-base Artifact
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "apisix-base-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"
          path: "./apisix-base-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"

      - name: Upload apisix-dashboard Artifact
        if: ${{ startsWith(steps.tag_type.outputs.version, 'dashboard/') }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "apisix-dashboard-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"
          path: "./apisix-dashboard-${{ steps.tag_env.outputs.version}}-0.el7.x86_64.rpm"

      - name: Sign apisix-base RPM Package
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
        env:
          GPG_NAME: "TZS APISIX Publish (Only For Test)"
          GPG_MAIL: "<tzssangglass@apisix.apache.org>"
          TAG_VERSION: ${{ steps.tag_env.outputs.version }}
          TARGET_APP: ${{ env.TARGET_APP }}
        run: |
          echo "${{ secrets.RPM_GPG_PRIV_KEY }}" >> /tmp/rpm-gpg-publish.private
          echo "${{ secrets.RPM_GPG_PUB_KEY }}" >> /tmp/rpm-gpg-publish.public
          echo "${{ secrets.RPM_GPG_PASSPHRASE }}" >> /tmp/rpm-gpg-publish.passphrase
          ./utils/publish-rpm.sh sign_target_app_rpm

      - name: Backup and rebuild RPM Repository
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
          TAG_VERSION: ${{ steps.tag_env.outputs.version }}
          TARGET_APP: ${{ env.TARGET_APP }}
        run: |
          ./utils/publish-rpm.sh backup_and_rebuild_repo

      - name: Sign RPM Repository Metadata
        env:
          TAG_VERSION: ${{ steps.tag_env.outputs.version }}
        run: |
          ./utils/publish-rpm.sh sign_repo_metadata

      - name: Upload new RPM Repository
        run: |
          ./utils/publish-rpm.sh upload_new_repo

      - name: Check download new apisix-base RPM Package
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
        env:
          TAG_VERSION: ${{ steps.tag_env.outputs.version }}
          TARGET_APP: ${{ env.TARGET_APP }}
        run: |
          ./utils/publish-rpm.sh check_down_load_apisix_base_rpm

      - name: Remove backup RPM Repository
        run: |
          ./utils/publish-rpm.sh rm_backup_repo
